In [68]:
import sklearn
import numpy as np
import os

# 노트북 실행 결과를 동일하게 유지하기 위해
np.random.seed(42)

#그래프 출력 모듈
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt


#Iris dataset
from sklearn import datasets
iris = datasets.load_iris()

X = iris["data"]  # 꽃잎 길이, 너비
y = iris["target"].astype(int)

In [69]:
import pandas as pd
print(y)    #number of class = 3

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [70]:
df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [71]:
print(df.max())
print("\n")
print(df.min())

sepal length (cm)    7.9
sepal width (cm)     4.4
petal length (cm)    6.9
petal width (cm)     2.5
dtype: float64


sepal length (cm)    4.3
sepal width (cm)     2.0
petal length (cm)    1.0
petal width (cm)     0.1
dtype: float64


In [72]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 11)

In [73]:
print(X_train.shape, y_train.shape)

(120, 4) (120,)


In [74]:
#Note that we know that there exists 3 class in iris set

#Gini Impurity
def Gini(samples_in_node):
    class_0 = 0
    class_1 = 0
    class_2 = 0
    
    for sample in samples_in_node:
        if sample[4] == 0:
            class_0 += 1
        elif sample[4] == 1:
            class_1 += 1
        elif sample[4] == 2:
            class_2 += 1
    gini = 1 - (((class_0/len(samples_in_node))**2)+((class_1/len(samples_in_node))**2)+((class_2/len(samples_in_node))**2))
    return gini

#Node Set Up
def insertNode(samples_in_node, feature : (int), threshold):
    leftChild = []
    rightChild = []
    for sample in samples_in_node:
        if sample[feature] < threshold:
            leftChild.append(sample)
        else:
            rightChild.append(sample)
    return rightChild, leftChild

#Loss Function
def Cost(samples_in_node, feature, threshold):
    left, right = insertNode(samples_in_node, feature, threshold)
    res = (len(left)/len(samples_in_node)*Gini(left)) + (len(right)/len(samples_in_node)*Gini(right))
    return res

In [75]:
from random import *

#data rebuild
new_set = np.zeros((len(X_train),5))
for i in range(len(X_train)):
    new_set[i, :4] = X_train[i]
    new_set[i, 4] = y_train[i]

Threshold = np.array([[4.3, 7.9], [2.0, 4.4], [1.0, 6.9], [0.1, 2.5]])
print(Threshold)

[[4.3 7.9]
 [2.  4.4]
 [1.  6.9]
 [0.1 2.5]]


In [76]:
new_set

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [6.9, 3.2, 5.7, 2.3, 2. ],
       [7.7, 2.8, 6.7, 2. , 2. ],
       [5. , 3.3, 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.6, 0.2, 0. ],
       [7.7, 2.6, 6.9, 2.3, 2. ],
       [7.6, 3. , 6.6, 2.1, 2. ],
       [6.7, 3. , 5. , 1.7, 1. ],
       [5.5, 3.5, 1.3, 0.2, 0. ],
       [6. , 2.7, 5.1, 1.6, 1. ],
       [5. , 2. , 3.5, 1. , 1. ],
       [7.9, 3.8, 6.4, 2. , 2. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [6.5, 3. , 5.8, 2.2, 2. ],
       [5.1, 2.5, 3. , 1.1, 1. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [5. , 3.2, 1.2, 0.2, 0. ],
       [7.4, 2.8, 6.1, 1.9, 2. ],
       [5.1, 3.8, 1.6, 0.2, 0. ],
       [6.8, 3.2, 5.9, 2.3, 2. ],
       [6.9, 3.1, 5.1, 2.3, 2. ],
       [5.9, 3. , 4.2, 1.5, 1. ],
       [4.9, 2.5, 4.5, 1.7, 2. ],
       [6.7, 3.1, 4.7, 1.5, 1. ],
       [4.4, 3.2, 1.3, 0.2, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [6.5, 2.8, 4.6, 1.5, 1. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [5. , 3

In [77]:
feature_1 = randint(0,3)
threshold_1 = uniform(Threshold[feature_1][0],Threshold[feature_1][1])
print(feature_1, threshold_1)
Cost(new_set, feature_1, threshold_1)

3 0.3233902445767427


0.4094961240310078

In [78]:
#depth 1
depth1_right, depth1_left = insertNode(new_set, feature_1, threshold_1)

print(Gini(depth1_right), Gini(depth1_left)) #Gini Impurity of Child Nodes

0.571389940508383 0.0


In [81]:
depth1_left

[array([5.1, 3.5, 1.4, 0.2, 0. ]),
 array([5. , 3.3, 1.4, 0.2, 0. ]),
 array([4.7, 3.2, 1.6, 0.2, 0. ]),
 array([5.5, 3.5, 1.3, 0.2, 0. ]),
 array([4.6, 3.4, 1.4, 0.3, 0. ]),
 array([5. , 3.2, 1.2, 0.2, 0. ]),
 array([5.1, 3.8, 1.6, 0.2, 0. ]),
 array([4.4, 3.2, 1.3, 0.2, 0. ]),
 array([5.4, 3.4, 1.7, 0.2, 0. ]),
 array([5.2, 3.4, 1.4, 0.2, 0. ]),
 array([5. , 3.6, 1.4, 0.2, 0. ]),
 array([5.1, 3.4, 1.5, 0.2, 0. ]),
 array([5.5, 4.2, 1.4, 0.2, 0. ]),
 array([4.6, 3.2, 1.4, 0.2, 0. ]),
 array([5.3, 3.7, 1.5, 0.2, 0. ]),
 array([5.7, 3.8, 1.7, 0.3, 0. ]),
 array([5.1, 3.5, 1.4, 0.3, 0. ]),
 array([4.4, 3. , 1.3, 0.2, 0. ]),
 array([5. , 3. , 1.6, 0.2, 0. ]),
 array([5.1, 3.8, 1.5, 0.3, 0. ]),
 array([5.2, 4.1, 1.5, 0.1, 0. ]),
 array([4.4, 2.9, 1.4, 0.2, 0. ]),
 array([4.6, 3.1, 1.5, 0.2, 0. ]),
 array([4.9, 3. , 1.4, 0.2, 0. ]),
 array([5. , 3.5, 1.3, 0.3, 0. ]),
 array([5. , 3.4, 1.5, 0.2, 0. ]),
 array([5.8, 4. , 1.2, 0.2, 0. ]),
 array([5.4, 3.7, 1.5, 0.2, 0. ]),
 array([5.2, 3.5, 1.

In [85]:
feature_2 = randint(0,3)
threshold_2 = uniform(Threshold[feature_2][0], Threshold[feature_2][1])
print(feature_2, threshold_2)

#depth 2
depth2_right, depth2_left = insertNode(depth1_right, feature_2, threshold_2)

print(Gini(depth2_right), Gini(depth2_left)) #Gini Impurity of Grandchild Nodes

1 3.1886662916440676
0.5532879818594105 0.4856804733727811


In [91]:
depth2_right

[array([6.9, 3.2, 5.7, 2.3, 2. ]),
 array([7.9, 3.8, 6.4, 2. , 2. ]),
 array([6.8, 3.2, 5.9, 2.3, 2. ]),
 array([5.1, 3.7, 1.5, 0.4, 0. ]),
 array([5. , 3.4, 1.6, 0.4, 0. ]),
 array([5.4, 3.4, 1.5, 0.4, 0. ]),
 array([6.3, 3.4, 5.6, 2.4, 2. ]),
 array([7.7, 3.8, 6.7, 2.2, 2. ]),
 array([5. , 3.5, 1.6, 0.6, 0. ]),
 array([6.3, 3.3, 6. , 2.5, 2. ]),
 array([7. , 3.2, 4.7, 1.4, 1. ]),
 array([6.7, 3.3, 5.7, 2.5, 2. ]),
 array([5.4, 3.9, 1.7, 0.4, 0. ]),
 array([6.4, 3.2, 5.3, 2.3, 2. ]),
 array([6.7, 3.3, 5.7, 2.1, 2. ]),
 array([5.1, 3.8, 1.9, 0.4, 0. ]),
 array([5.1, 3.3, 1.7, 0.5, 0. ]),
 array([5.9, 3.2, 4.8, 1.8, 1. ]),
 array([6.2, 3.4, 5.4, 2.3, 2. ]),
 array([7.2, 3.2, 6. , 1.8, 2. ]),
 array([7.2, 3.6, 6.1, 2.5, 2. ])]

In [107]:
from collections import Counter

y1 = np.array(depth2_right)[:, 4]
y2 = np.array(depth2_left)[:, 4]
cnt1 = Counter(y1)
cnt2 = Counter(y2)
print(cnt1, cnt2)

Counter({2.0: 12, 0.0: 7, 1.0: 2}) Counter({1.0: 38, 2.0: 27})


In [109]:
#Test (feature와 threshold는 위에서 임의대로 구해진 대로 진행, 편의를 위해 소숫점 둘째자리 반올림)
#Test set으로 진행, 위 훈련에서 노드의 진행과 최빈값 기준으로 y_pred 구성
y_pred_handmade = []

for sample in X_test:
    if sample[0] <= 0.3:
        y_pred_handmade.append(0)
    else:
        if sample[1] <= 3.2:
            y_pred_handmade.append(1)
        else:
            y_pred_handmade.append(2)

In [111]:
#성능 척도: 오차행렬
from sklearn.metrics import confusion_matrix
mat = confusion_matrix(y_test, y_pred_handmade)
mat

array([[ 0,  5,  4],
       [ 0,  8,  2],
       [ 0, 11,  0]], dtype=int64)

In [113]:
#Using Python Module
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(max_depth=2, random_state=11)
tree.fit(X_train, y_train)
y_pred_module = tree.predict(X_test)

mat = confusion_matrix(y_test, y_pred_module)
mat

array([[9, 0, 0],
       [0, 8, 2],
       [0, 2, 9]], dtype=int64)