In [1]:
import sklearn
import numpy as np
import os
import pandas as pd

np.random.seed(42)

%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt

#Iris dataset
from sklearn import datasets
iris = datasets.load_iris()
list(iris.keys())
X = iris["data"][:, 2:]  # 꽃잎 길이, 꽃잎 너비
y = (iris["target"] == 2).astype(int)  # Iris virginica이면 1 아니면 0

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=10)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

y_train_abs1 = y_train * 2 - 1
y_test_abs1 = y_test * 2 - 1
print(y_train_abs1)

[ 1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1 -1  1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1
  1 -1  1 -1  1 -1 -1 -1 -1  1  1  1  1  1 -1 -1  1 -1 -1  1 -1 -1 -1 -1
 -1 -1  1  1 -1 -1 -1 -1  1  1 -1 -1  1  1  1  1 -1 -1 -1 -1 -1 -1  1 -1
 -1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1  1 -1  1 -1 -1 -1  1  1 -1 -1  1  1
 -1 -1  1 -1  1 -1 -1 -1 -1  1  1  1 -1 -1  1 -1]


In [35]:
#에타 업데이트 용 함수
t0 = 10
t1 = 100
def learning_schedule(t):
    return t0 / (t + t1) 

#definition of f(x)
w = np.random.randn(2) 
b = np.random.randn(1) #initialization
def f(x):
    return w.T.dot(x) + b

#람다
C=5
const_lambda = 2/C

#gradient (with repect to w) update
def gradient_wrt_w(x, y):
    if y * f(x) < 1:
        return const_lambda * w - y * x
    else:
        return const_lambda * w

In [36]:
n_epochs = 1000
m = len(X_train)

for epoch in range(n_epochs):
    for i in range(m):
        random_index = np.random.randint(m)
        xi = X_train[random_index]
        yi = y_train[random_index]
        eta = learning_schedule(epoch)
        w = w - eta * gradient_wrt_w(xi, yi)

In [37]:
w

array([0.85780347, 0.85901598])

In [38]:
#get final values
y_pred = []
for xi in X_test:
    if f(xi) > 0:
        y_pred.append(1)
    else:
        y_pred.append(0)
y_pred = np.array(y_pred)

#confusion matrix of this svm training applied sgd
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[26,  0],
       [ 1, 11]], dtype=int64)

In [14]:
#using module
from sklearn.svm import SVC
svm_clf = SVC(kernel="linear", C=5)
svm_clf.fit(X_train, y_train_abs1)
svm_clf_pred = svm_clf.predict(X_test)

y_confusion_matrix = confusion_matrix(y_test_abs1, svm_clf_pred)
y_confusion_matrix

array([[26,  0],
       [ 0, 12]], dtype=int64)