In [60]:
import numpy as mp
import pandas as pd
os.getcwd()

'C:\\Users\\people\\빅데이터기계학습'

In [40]:
train_titanic = pd.read_csv('train.csv')

In [41]:
train_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [42]:
train_titanic.drop("Cabin", inplace=True, axis=1)

In [46]:
train_titanic.dropna(subset=['Embarked'], inplace = True)
train_titanic.fillna(train_titanic['Age'].median(), inplace = True)
train_titanic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  889 non-null    int64  
 1   Survived     889 non-null    int64  
 2   Pclass       889 non-null    int64  
 3   Name         889 non-null    object 
 4   Sex          889 non-null    object 
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64  
 7   Parch        889 non-null    int64  
 8   Ticket       889 non-null    object 
 9   Fare         889 non-null    float64
 10  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(4)
memory usage: 83.3+ KB


In [59]:
corr_mat_titanic = train_titanic.corr()
corr_mat_titanic['Survived'].sort_values(ascending=False)

Survived       1.000000
Fare           0.255290
Parch          0.083151
PassengerId   -0.005028
SibSp         -0.034040
Age           -0.069822
Pclass        -0.335549
Name: Survived, dtype: float64

In [51]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
train_sex = encoder.fit_transform(train_titanic[["Sex"]])
train_embarked = encoder.fit_transform(train_titanic[["Embarked"]])
print(train_sex.toarray())
print(train_embarked.toarray())

[[0. 1.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [0. 1.]
 [0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 ...
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
